### ISSUE TITLE
infinite scroll on product list page "Enhancement" 

### ISSUE THREAD

**Issue by Almusamim** [PrestaShop/classic-rocket#11]
This would be a really nice feature to add to this theme.
Also a Shop now days should have an infinite scroll.. instead of having to click on the next button all the time.

Please consider this

**Comment by prestarocket** [comment]
IMO infinite scroll is not a solution for every store:

- https://www.smashingmagazine.com/2016/03/pagination-infinite-scrolling-load-more-buttons/
- https://speckyboy.com/infinite-scrolling/
- https://ux.stackexchange.com/questions/33406/infinite-scroll-vs-pagination-in-e-commerce-websites

sorry, i will not add this feature.

**Comment by mortenhartvig** [comment]
@prestarocket - agree. Although, it would probably be a good idea having a "load more products" feature (with lazy loading) instead of the 1, 2, 3, 4 page buttons. 

Appending products with lazy loading, could be far better than what Prestashop currently does with classic. We are going to do this at some point in our own webshop. 

Brilliant work in general btw. We are going to merge your work into our fork of classic soon. Would love the "load more products" feature, so i don't have to do it myself :) 👍
