### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by kenlog** [PrestaShop/classic-rocket#156]
Why don't you use semantic version specifications for theme releases?
I am referring above all to the backward compatible additions/changes to the API that do not increase the Minor version. :confused:

**Comment by prestarocket** [comment]
I'm sorry, I'm still not very comfortable with semantic version specifications; what would be the right version ?

**Comment by matks** [comment]
> I'm sorry, I'm still not very comfortable with semantic version specifications; what would be the right version ?

Hi ! If I can help 😉

SemVer is x.y.z

- if new version contains only bugfixes, increase z by 1 ⏩new patch release: like previous version but with less bugs (or faster)
- if new version contains new features / enhancements **but no breaking changes**, increase y by 1 ⏩ new minor release : like previous version but with less bugs and some new cool things
- if new version contains breaking changes that require users to modify how they integrate the theme, increase x by 1 : a new version

This is really useful for users because they know
- if it's a patch release, I can upgrade without worries, it cannot hurt
- if it's a minor release, I can upgrade but better check what's new it could be cool
- if it's a major release, I need to explore it and test it

**Comment by prestarocket** [comment]
so it s 3.0.0 , thx @matks

**Comment by kenlog** [comment]
@prestarocket I'm sorry I didn't answer you right away. However @matks was very exhaustive!
